CREATE TABLE ANIMAL
(
  ANIMAL_ID NUMBER NOT NULL AUTO_INCREMENT
, NOM_ANIMAL VARCHAR2(30) 
, DESCRIPTION VARCHAR2(60)
, PRIMARY KEY (ANIMAL_ID)
  ENABLE 
);

INSERT INTO ANIMAL (NOM_ANIMAL, DESCRIPTION)
VALUES ( );
